### PR TITLE
Fix @channel / @channels ambiguity and issue #172

### LINKED ISSUE #172: Pushing to 'ios' channel gives "Parse::ParseProtocolError: 115: Can't set channels for a query-targeted push."
Just attempting a simple push via Parse. This is almost straight from the README.

Gemfile:

`gem 'parse-ruby-client', git: 'git://github.com/adelevie/parse-ruby-client.git'`

Commit SHA is `cac0493`.

---
### This returns an error:

```ruby
parse = Parse.create(
    application_id: ENV['parse_application_id'],
    api_key: ENV['parse_api_key'],
    quiet: false)

push = parse.push({alert: 'Hello.'}, 'user_e3929e0df56e163acc3072df2b2748')

push.type='ios'

push.save
```

Response:

```
I, [2015-06-17T13:47:18.870459 #9008]  INFO -- : post https://api.parse.com/1/push
I, [2015-06-17T13:47:19.329457 #9008]  INFO -- Status: 400
Parse::ParseProtocolError: 115: Can't set channels for a query-targeted push.
from /opt/boxen/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/parse-ruby-client-cac04938900c/lib/faraday/extended_parse_json.rb:25:in `process_response'
```

---
### This works fine:

```ruby
push = parse.push({alert: 'Hello.'}, 'user_e3929e0df56e163acc3072df2b2748')
# Don't set the type
push.save
```

Response:
```
I, [2015-06-17T13:53:29.577909 #9008]  INFO -- : post https://api.parse.com/1/push
I, [2015-06-17T13:53:30.024296 #9008]  INFO -- Status: 200
=> {"result"=>true}
```

---

Sorry, but what am I missing, or this a bug?

### PR DESCRIPTION
**Pull request by rhymes**
I removed the the @channel attribute because the behavior of the library
is confusing if someone specifies both the channel during initialization
and sets @channels later on.

This way we only use @channels which is an obvious array of @channels someone
wants to target and the channel given in the initialization ends up there.

I also fixed #172 by making it so that automatically the channels end up in
the where condition if @type is specified at the same time. Parse does not support both `deviceType` and `channel`  at the same time outside the where condition: https://parse.com/questions/cant-set-channels-for-a-query-targeted-push

### CODE REVIEW

**Comment by rhymes** [comment]
@Xavdidtheshadow @adelevie any input on this?

File: lib/parse/push.rb [hunk 1]
```diff
@@ -17,32 +16,35 @@ class Push
...
       @data = data
 
+      # NOTE: if no channel is specified, by setting "where" to an empty clause
+      #   a push is sent to all clients.
       if !channel || channel.empty?
-        # If no channel is specified, by setting "where" to an empty clause, a push is sent to all clients.
         @where = {}
       else
-        @channel = channel
+        @channels = [channel]
```
Comment (jastkand) [inline lib/parse/push.rb]: May be it's better to do this like `@channels = *channel` in order to be able to pass array of channels on initialization? Also it looks strange for me that we are using empty string as a default value for channel param `def initialize(data, channel = '', client = nil)`. Why not to use `nil` instead?

Comment (rhymes) [inline lib/parse/push.rb]: I don't think we should change the public interface of the initializer nor it should be a catch all (which actually adds ambiguity and I'm trying to remove it). It works like this:

- if you need to target one channel you can pass the string to `initialize` and be done with it
- if you have a list of channel just use the `channels` attribute and provide a list
- the channel you provide ends up in the `channels` attribute anyway so you have only *one place* to look (instead of `channel` and `channels` right now) to know which channels the push is targeting.

Channel defaults to an empty string because it accepts a string. It seemed the obvious choice between the two.

**Comment by Xavdidtheshadow** [comment]
@rhymes Looks good! I'll admit, I don't know much about channels, but the code seems good. 

Also, is it worth gitignoring  `.rubocop_todo.yml` so that it doesn't take up so much space on the pull requests?

**Comment by rhymes** [comment]
@Xavdidtheshadow we can't gitignore it, it's how Rubocop keeps track of what's temporarily hidden. The pattern is to write code, ignore all the warnings, remove one warning at the time, fix the code, repeat.

**Comment by Xavdidtheshadow** [comment]
@rhymes cool! then yeah I vote merge. I trust you know what you're doing.

**Comment by rhymes** [comment]
Done
